[package]
name = "bevy_cloth"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]

[dependencies.bevy]
version = "0.7"
default-features = false
features = ["render"]

[dev-dependencies]

[dev-dependencies.bevy]
version = "0.7"
features = ["render", "bevy_winit", "x11"]
default-features = false

[[example]]
name = "balloon_example"