[package]
name = "bevy_cloth"
version = "0.1.0"
edition = "2021"
authors = ["Felix de Maneville <felix.maneville@gmail.com>"]
repository = "https://github.com/ManevilleF/bevy_cloth"
license-file = "./LICENSE"
exclude = ["docs"]
description = "Cloth physics implementation in bevy"
keywords = ["verlet", "physics", "bevy", "cloth"]
categories = ["game-engines", "game-development"]
readme = "README.md"
documentation = "https://docs.rs/bevy_cloth"

[features]
default = []

[dependencies]
bevy_app = "0.7"
bevy_utils = "0.7"
bevy_ecs = "0.7"
bevy_render = "0.7"
bevy_math = "0.7"
bevy_log = "0.7"
bevy_transform = "0.7"
bevy_core = "0.7"
bevy_asset = "0.7"

[dev-dependencies]

[dev-dependencies.bevy]
version = "0.7"
features = ["render", "bevy_winit", "x11"]
default-features = false

[[example]]
name = "balloon_example"