[package]
name = "bevy_cloth"
version = "0.1.0"
edition = "2021"

[features]
default = []
debug = ["bevy-inspector-egui"]

[dependencies]

[dependencies.bevy]
version = "0.7"
default-features = false
features = ["render"]

[dependencies.bevy-inspector-egui]
version = "0.10"
optional = true
default-features = false
features = ["clipboard", "bevy_pbr"]

[dev-dependencies]
bevy-inspector-egui = "0.10"

[dev-dependencies.bevy]
version = "0.7"
features = ["render", "bevy_winit", "x11"]
default-features = false

[[example]]
name = "basic_example"
required-features = ["debug"]